export const USER_AUTHENTICATE = 'USER_AUTHENTICATE'
export const USER_AUTHENTICATE_SUCCESS = 'USER_AUTHENTICATE_SUCCESS'
export const USER_AUTHENTICATE_FAILURE = 'USER_AUTHENTICATE_FAILURE'
export const USER_AUTHENTICATE_HIDE_ERROR = 'USER_AUTHENTICATE_HIDE_ERROR'
export const USER_GET_MENU_OPTIONS = 'USER_GET_MENU_OPTIONS'
export const USER_GET_MENU_OPTIONS_SUCESS = 'USER_GET_MENU_OPTIONS_SUCESS'
export const USER_GET_MENU_OPTIONS_FAILURE = 'USER_GET_MENU_OPTIONS_FAILURE'
export const PARTNERS_GET_PARTNERS = 'PARTNERS_GET_PARTNERS'
export const PARTNERS_GET_PARTNERS_SUCCESS = 'PARTNERS_GET_PARTNERS_SUCCESS'
export const PARTNERS_GET_PARTNERS_FAILURE = 'PARTNERS_GET_PARTNERS_FAILURE'
export const GENERAL_GET_NATIONALITIES = 'GENERAL_GET_NATIONALITIES'
export const GENERAL_GET_NATIONALITIES_SUCCESS =
  'GENERAL_GET_NATIONALITIES_SUCCESS'
export const GENERAL_GET_NATIONALITIES_FAILURE =
  'GENERAL_GET_NATIONALITIES_FAILURE'
export const GENERAL_GET_DGII = 'GENERAL_GET_DGII'
export const GENERAL_GET_DGII_SUCCESS = 'GENERAL_GET_DGII_SUCCESS'
export const GENERAL_GET_DGII_FAILURE = 'GENERAL_GET_DGII_FAILURE'
export const GET_PARAM_LISTS = 'GET_PARAM_LISTS'
export const GET_PARAM_LISTS_SUCCESS = 'GET_PARAM_LISTS_SUCCESS'
export const GET_PARAM_LISTS_FAILURE = 'GET_PARAM_LISTS_FAILURE'
export const GET_PARAM_LIST = 'GET_PARAM_LIST'
export const GET_PARAM_LIST_SUCCESS = 'GET_PARAM_LIST_SUCCESS'
export const GET_PARAM_LIST_FAILURE = 'GET_PARAM_LIST_FAILURE'

export const GENERAL_GET_PROVINCES = 'GENERAL_GET_PROVINCES'
export const GENERAL_GET_PROVINCES_SUCCESS = 'GENERAL_GET_PROVINCES_SUCCESS'
export const GENERAL_GET_PROVINCES_FAILURE = 'GENERAL_GET_PROVINCES_FAILURE'
export const GENERAL_GET_MUNICIPALITIES = 'GENERAL_GET_MUNICIPALITIES'
export const GENERAL_GET_MUNICIPALITIES_FAILURE =
  'GENERAL_GET_MUNICIPALITIES_FAILURE'
export const GENERAL_GET_MUNICIPALITIES_SUCCESS =
  'GENERAL_GET_MUNICIPALITIES_SUCCESS'

export const GENERAL_GET_SECTORS = 'GENERAL_GET_SECTORS'
export const GENERAL_GET_SECTORS_SUCCESS = 'GENERAL_GET_SECTORS_SUCCESS'
export const GENERAL_GET_SECTORS_FAILURE = 'GENERAL_GET_SECTORS_FAILURE'
export const GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES =
  'GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES'
export const GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES_SUCCESS =
  'GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES_SUCCESS'
export const GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES_FAILURE =
  'GENERAL_GET_CLIENT_RELATED_REPRESENTATIVES_FAILURE'

export const POST_CLIENT = 'POST_CLIENT'
export const POST_CLIENT_SUCCESS = 'POST_CLIENT_SUCCESS'
export const POST_CLIENT_FAILURE = 'POST_CLIENT_FAILURE'

export const GENERAL_GET_ACTIVITY_PARAMETERS = 'GENERAL_GET_ACTIVITY_PARAMETERS'
export const GENERAL_GET_ACTIVITY_PARAMETERS_SUCCESS =
  'GENERAL_GET_ACTIVITY_PARAMETERS_SUCCESS'
export const GENERAL_GET_ACTIVITY_PARAMETERS_FAILURE =
  'GENERAL_GET_ACTIVITY_PARAMETERS_FAILURE'

export const POST_CLIENT_DIRECTION = 'POST_CLIENT_DIRECTION'
export const POST_CLIENT_DIRECTION_SUCCESS = 'POST_CLIENT_DIRECTION_SUCCESS'
export const POST_CLIENT_DIRECTION_FAILURE = 'POST_CLIENT_DIRECTION_FAILURE'

export const GENERAL_GET_PHONE_TYPES = 'GENERAL_GET_PHONE_TYPES'
export const GENERAL_GET_PHONE_TYPES_SUCCESS = 'GENERAL_GET_PHONE_TYPES_SUCCESS'
export const GENERAL_GET_PHONE_TYPES_FAILURE = 'GENERAL_GET_PHONE_TYPES_FAILURE'

export const GENERAL_GET_VEHICLE_BRANDS = 'GENERAL_GET_VEHICLE_BRANDS'
export const GENERAL_GET_VEHICLE_BRANDS_SUCCESS =
  'GENERAL_GET_VEHICLE_BRANDS_SUCCESS'
export const GENERAL_GET_VEHICLE_BRANDS_FAILURE =
  'GENERAL_GET_VEHICLE_BRANDS_FAILURE'

export const GENERAL_POST_CRM_CAPTACION_PROSPECTO =
  'GENERAL_POST_CRM_CAPTACION_PROSPECTO'
export const GENERAL_POST_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'GENERAL_POST_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const GENERAL_POST_CRM_CAPTACION_PROSPECTO_FAILURE =
  'GENERAL_POST_CRM_CAPTACION_PROSPECTO_FAILURE'

export const GENERAL_GET_MODEL_VEHICLE = 'GENERAL_GET_MODEL_VEHICLE'
export const GENERAL_GET_MODEL_VEHICLE_SUCCESS =
  'GENERAL_GET_MODEL_VEHICLE_SUCCESS'
export const GENERAL_GET_MODEL_VEHICLE_FAILURE =
  'GENERAL_GET_MODEL_VEHICLE_FAILURE'

export const GENERAL_GET_VEHICLE_STYLE = 'GENERAL_GET_VEHICLE_STYLE'
export const GENERAL_GET_VEHICLE_STYLE_SUCCESS =
  'GENERAL_GET_VEHICLE_STYLE_SUCCESS'
export const GENERAL_GET_VEHICLE_STYLE_FAILURE =
  'GENERAL_GET_VEHICLE_STYLE_FAILURE'

export const POST_CRM_PHONE_PROSPECT = 'POST_CRM_PHONE_PROSPECT'
export const POST_CRM_PHONE_PROSPECT_SUCCESS = 'POST_CRM_PHONE_PROSPECT_SUCCESS'
export const POST_CRM_PHONE_PROSPECT_FAILURE = 'POST_CRM_PHONE_PROSPECT_FAILURE'

export const POST_PERSONAL_SURE = 'POST_PERSONAL_SURE'
export const POST_PERSONAL_SURE_FAILURE = 'POST_PERSONAL_SURE_FAILURE'
export const POST_PERSONAL_SURE_SUCCESS = 'POST_PERSONAL_SURE_SUCCESS'

export const PUT_CRM_VEHICULE_PICKUP = 'PUT_CRM_VEHICULE_PICKUP'
export const POST_CRM_VEHICULE_PICKUP = 'POST_CRM_VEHICULE_PICKUP'

export const POST_CRM_VEHICULE_PICKUP_SUCCESS =
  'POST_CRM_VEHICULE_PICKUP_SUCCESS'
export const POST_CRM_VEHICULE_PICKUP_FAILURE =
  'POST_CRM_VEHICULE_PICKUP_FAILURE'
export const GENERAL_GET_COUNTRIES = 'GENERAL_GET_COUNTRIES'
export const GENERAL_GET_COUNTRIES_SUCCESS = 'GENERAL_GET_COUNTRIES_SUCCESS'
export const GENERAL_GET_COUNTRIES_FAILURE = 'GENERAL_GET_COUNTRIES_FAILURE'
export const GENERAL_GET_COINS = 'GENERAL_GET_COINS'
export const GENERAL_GET_COINS_SUCCESS = 'GENERAL_GET_COINS_SUCCESS'
export const GENERAL_GET_COINS_FAILURE = 'GENERAL_GET_COINS_FAILURE'

export const GENERAL_GET_TYPE_TELEPHONE = 'GENERAL_GET_TYPE_TELEPHONE'
export const GENERAL_GET_TYPE_TELEPHONE_SUCCESS =
  'GENERAL_GET_TYPE_TELEPHONE_SUCCESS'
export const GENERAL_GET_TYPE_TELEPHONE_FAILURE =
  'GENERAL_GET_TYPE_TELEPHONE_FAILURE'

export const GENERAL_GET_TELEPHONE = 'GENERAL_GET_TELEPHONE'
export const GENERAL_GET_TELEPHONE_SUCCESS = 'GENERAL_GET_TELEPHONE_SUCCESS'
export const GENERAL_GET_TELEPHONE_FAILURE = 'GENERAL_GET_TELEPHONE_FAILURE'
export const SET_GENERAL_STORE_DATA = 'SET_GENERAL_STORE_DATA'
export const SET_GENERAL_STORE_2_DATA = 'SET_GENERAL_STORE_2_DATA'

export const GENERAL_GET_VEHICLE_TYPE = 'GENERAL_GET_VEHICLE_TYPE'
export const GENERAL_GET_VEHICLE_TYPE_SUCCESS =
  'GENERAL_GET_VEHICLE_TYPE_SUCCESS'
export const GENERAL_GET_VEHICLE_TYPE_FAILURE =
  'GENERAL_GET_VEHICLE_TYPE_FAILURE'

export const GENERAL_POST_TELEPHONE = 'GENERAL_POST_TELEPHONE'
export const GENERAL_POST_TELEPHONE_SUCCESS = 'GENERAL_POST_TELEPHONE_SUCCESS'
export const GENERAL_POST_TELEPHONE_FAILURE = 'GENERAL_POST_TELEPHONE_FAILURE'

export const GET_PROSPECTO_ASESOR_VENTA = 'GET_PROSPECTO_ASESOR_VENTA'
export const GET_PROSPECTO_ASESOR_VENTAT_SUCCESS =
  'GET_PROSPECTO_ASESOR_VENTAT_SUCCESS'
export const GET_PROSPECTO_ASESOR_VENTA_FAILURE =
  'GET_PROSPECTO_ASESOR_VENTA_FAILURE'

export const POST_ANALISIS_CREDIT = 'POST_ANALISIS_CREDIT'
export const POST_ANALISIS_CREDIT_SUCCESS = 'POST_ANALISIS_CREDIT_SUCCESS'
export const POST_ANALISIS_CREDIT_FAILURE = 'POST_ANALISIS_CREDIT_FAILURE'

export const GET_VEHICLE_INTER = 'GET_VEHICLE_INTER'
export const GET_VEHICLE_INTER_SUCCESS = 'GET_VEHICLE_INTER_SUCCESS'
export const GET_VEHICLE_INTER_FAILURE = 'GET_VEHICLE_INTER_FAILURE'
export const GENERAL_GET__LEAFLET_AFC = 'GENERAL_GET__LEAFLET_AFC'
export const GENERAL_GET__LEAFLET_AFC_FAILURE =
  'GENERAL_GET__LEAFLET_AFC_FAILURE'
export const GENERAL_GET__LEAFLET_AFC_SUCCESS =
  'GENERAL_GET__LEAFLET_AFC_SUCCESS'

export const POST_CONSULT_CRM_CAPTACION_PROSPECTO =
  'POST_CONSULT_CRM_CAPTACION_PROSPECTO'
export const POST_CONSULT_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'POST_CONSULT_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const POST_CONSULT_CRM_CAPTACION_PROSPECTO_FAILURE =
  'POST_CONSULT_CRM_CAPTACION_PROSPECTO_FAILURE'

export const PUT_CRM_CAPTACION_PROSPECTO = 'PUT_CRM_CAPTACION_PROSPECTO'
export const PUT_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'PUT_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const PUT_CRM_CAPTACION_PROSPECTO_FAILURE =
  'PUT_CRM_CAPTACION_PROSPECTO_FAILURE'
export const POST_VEHICLE_RELATIONSHIP = 'POST_VEHICLE_RELATIONSHIP'
export const POST_VEHICLE_RELATIONSHIP_SUCCESS =
  'POST_VEHICLE_RELATIONSHIP_SUCCESS'
export const POST_VEHICLE_RELATIONSHIP_FAILURE =
  'POST_VEHICLE_RELATIONSHIP_FAILURE'

export const POST_CRM_LIST_ANALIS_CREDIT = 'POST_CRM_LIST_ANALIS_CREDIT'
export const POST_CRM_LIST_ANALIS_CREDIT_SUCCESS =
  'POST_CRM_LIST_ANALIS_CREDIT_SUCCESS'
export const POST_CRM_LIST_ANALIS_CREDIT_FAILURE =
  'POST_CRM_LIST_ANALIS_CREDIT_FAILURE'
export const POST_ADD_CRM_CAPTACION_PROSPECTO =
  'POST_ADD_CRM_CAPTACION_PROSPECTO'
export const POST_ADD_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'POST_ADD_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const POST_ADD_CRM_CAPTACION_PROSPECTO_FAILURE =
  'POST_ADD_CRM_CAPTACION_PROSPECTO_FAILURE'

export const PUT_UPDATE_CRM_CAPTACION_PROSPECTO =
  'PUT_UPDATE_CRM_CAPTACION_PROSPECTO'
export const PUT_UPDATE_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'PUT_UPDATE_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const PUT_UPDATE_CRM_CAPTACION_PROSPECTO_FAILURE =
  'PUT_UPDATE_CRM_CAPTACION_PROSPECTO_FAILURE'
export const GET_FINANCING_OFFERS = 'GET_FINANCING_OFFERS'
export const GET_FINANCING_OFFERS_SUCCESS = 'GET_FINANCING_OFFERS_SUCCESS'
export const GET_FINANCING_OFFERS_FAILURE = 'GET_FINANCING_OFFERS_FAILURE'

export const GET_FINANCIAL_ENTITIES = 'GET_FINANCIAL_ENTITIES'
export const GET_FINANCIAL_ENTITIES_SUCCESS = 'GET_FINANCIAL_ENTITIES_SUCCESS'
export const GET_FINANCIAL_ENTITIES_FAILURE = 'GET_FINANCIAL_ENTITIES_FAILURE'

export const POST_VEHICLE_RECIEVE = 'POST_VEHICLE_RECIEVE'
export const POST_VEHICLE_RECIEVE_SUCCESS = 'POST_VEHICLE_RECIEVE_SUCCESS'
export const POST_VEHICLE_RECIEVE_FAILURE = 'POST_VEHICLE_RECIEVE_FAILURE'

export const POST_CRM_ANALIS_CREDIT = 'POST_CRM_ANALIS_CREDIT'
export const POST_CRM_ANALIS_CREDIT_SUCCESS = 'POST_CRM_ANALIS_CREDIT_SUCCESS'
export const POST_CRM_ANALIS_CREDIT_FAILURE = 'POST_CRM_ANALIS_CREDIT_FAILURE'

export const POST_CRM_ANALIS_CREDIT_INF = 'POST_CRM_ANALIS_CREDIT_INF'
export const POST_CRM_ANALIS_CREDIT_INF_SUCCESS =
  'POST_CRM_ANALIS_CREDIT_INF_SUCCESS'
export const POST_CRM_ANALIS_CREDIT_INF_FAILURE =
  'POST_CRM_ANALIS_CREDIT_INF_FAILURE'

export const POST_CRM_SEGUIMIENTO = 'POST_CRM_SEGUIMIENTO'
export const POST_CRM_SEGUIMIENTO_SUCCESS = 'POST_CRM_SEGUIMIENTO_SUCCESS'
export const POST_CRM_SEGUIMIENTO_FAILURE = 'POST_CRM_SEGUIMIENTO_FAILURE'

export const GET_VENDEDORES = 'GET_VENDEDORES'
export const GET_VENDEDORES_SUCCESS = 'GET_VENDEDORES_SUCCESS'
export const GET_VENDEDORES_FAILURE = 'GET_VENDEDORES_FAILURE'

export const POST_SOL_APPRAISAL = 'POST_SOL_APPRAISAL'
export const POST_SOL_APPRAISAL_SUCCESS = 'POST_SOL_APPRAISAL_SUCCESS'
export const POST_SOL_APPRAISAL_FAILURE = 'POST_SOL_APPRAISAL_FAILURE'

export const POST_CONS_BODY_TYPE = 'POST_CONS_BODY_TYPE'
export const POST_CONS_BODY_TYPE_SUCCESS = 'POST_CONS_BODY_TYPE_SUCCESS'
export const POST_CONS_BODY_TYPE_FAILURE = 'POST_CONS_BODY_TYPE_FAILURE'

export const PUT_CRM_PICKUP_VEHICULE = 'PUT_CRM_PICKUP_VEHICULE'
export const PUT_CRM_PICKUP_VEHICULE_SUCCESS = 'PUT_CRM_PICKUP_VEHICULE_SUCCESS'
export const PUT_CRM_PICKUP_VEHICULE_FAILURE = 'PUT_CRM_PICKUP_VEHICULE_FAILURE'

export const POST_INSERT_PARTS_TO_PAINT = 'POST_INSERT_PARTS_TO_PAINT'
export const POST_INSERT_PARTS_TO_PAINT_SUCCESS =
  'POST_INSERT_PARTS_TO_PAINT_SUCCESS'
export const POST_INSERT_PARTS_TO_PAINT_FAILURE =
  'POST_INSERT_PARTS_TO_PAINT_FAILURE'

export const POST_INSERT_ACCIDENTS = 'POST_INSERT_ACCIDENTS'
export const POST_INSERT_ACCIDENTS_SUCCESS = 'POST_INSERT_ACCIDENTS_SUCCESS'
export const POST_INSERT_ACCIDENTS_FAILURE = 'POST_INSERT_ACCIDENTS_FAILURE'

export const POST_CONSUL_SOL_APPRAISAL = 'POST_CONSUL_SOL_APPRAISAL'
export const POST_CONSUL_SOL_APPRAISAL_SUCCESS =
  'POST_CONSUL_SOL_APPRAISAL_SUCCESS'
export const POST_CONSUL_SOL_APPRAISAL_FAILURE =
  'POST_CONSUL_SOL_APPRAISAL_FAILURE'

export const POST_CONSUL_APPRAISAL_DETAILS = 'POST_CONSUL_APPRAISAL_DETAILS'
export const POST_CONSUL_APPRAISAL_DETAILS_SUCCESS =
  'POST_CONSUL_APPRAISAL_DETAILS_SUCCESS'
export const POST_CONSUL_APPRAISAL_DETAILS_FAILURE =
  'POST_CONSUL_APPRAISAL_DETAILS_FAILURE'

export const GET_LIST_PARAMETERS_DET = 'GET_LIST_PARAMETERS_DET_1'
export const GET_LIST_PARAMETERS_DET_SUCCESS =
  'GET_LIST_PARAMETERS_DET_1_SUCCESS'
export const GET_LIST_PARAMETERS_DET_FAILURE =
  'GET_LIST_PARAMETERS_DET_1_FAILURE'

export const GET_INTERIOR_AREA = 'GET_INTERIOR_AREA'
export const GET_INTERIOR_AREA_SUCCESS = 'GET_INTERIOR_AREA_SUCCESS'
export const GET_INTERIOR_AREA_FAILURE = 'GET_INTERIOR_AREA_FAILURE'

export const GET_TRUNK_AREA = 'GET_TRUNK_AREA'
export const GET_TRUNK_AREA_SUCCESS = 'GET_TRUNK_AREA_SUCCESS'
export const GET_TRUNK_AREA_FAILURE = 'GET_TRUNK_AREA_FAILURE'

export const GET_RUBBERS = 'GET_RUBBERS'
export const GET_RUBBERS_SUCCESS = 'GET_RUBBERS_SUCCESS'
export const GET_RUBBERS_FAILURE = 'GET_RUBBERS_FAILURE'

export const POST_CLIENTE_LIST = 'POST_CLIENTE_LIST'
export const POST_CLIENTE_LIST_SUCCESS = 'POST_CLIENTE_LIST_SUCCESS'
export const POST_CLIENTE_LIST_FAILURE = 'POST_CLIENTE_LIST_FAILURE'

export const POST_VEHICLE_APPRAISAL = 'POST_VEHICLE_APPRAISAL'
export const POST_VEHICLE_APPRAISAL_SUCCESS = 'POST_VEHICLE_APPRAISAL_SUCCESS'
export const POST_VEHICLE_APPRAISAL_FAILURE = 'POST_VEHICLE_APPRAISAL_FAILURE'

export const POST_CONSUL_BUSINESS_APPLICATION =
  'POST_CONSUL_BUSINESS_APPLICATION'
export const POST_CONSUL_BUSINESS_APPLICATION_SUCCESS =
  'POST_CONSUL_BUSINESS_APPLICATION_SUCCESS'
export const POST_CONSUL_BUSINESS_APPLICATION_FAILURE =
  'POST_CONSUL_BUSINESS_APPLICATION_FAILURE'

export const POST_CONSUL_ASSIGN_MANAGER = 'POST_CONSUL_ASSIGN_MANAGER'
export const POST_CONSUL_ASSIGN_MANAGER_SUCCESS =
  'POST_CONSUL_ASSIGN_MANAGER_SUCCESS'
export const POST_CONSUL_ASSIGN_MANAGER_FAILURE =
  'POST_CONSUL_ASSIGN_MANAGER_FAILURE'
export const POST_CRM_CREDIT_ANALYSIS = 'POST_CRM_CREDIT_ANALYSIS'
export const POST_CRM_CREDIT_ANALYSIS_SUCCESS =
  'POST_CRM_CREDIT_ANALYSIS_SUCCESS'
export const POST_CRM_CREDIT_ANALYSIS_FAILURE =
  'POST_CRM_CREDIT_ANALYSIS_FAILURE'

export const POST_CONSUL_CRM_PROSPECTO = 'POST_CONSUL_CRM_PROSPECTOS'
export const POST_CONSUL_CRM_PROSPECTO_SUCCESS =
  'POST_CONSUL_CRM_PROSPECTO_SUCCESS'
export const POST_CONSUL_CRM_PROSPECTO_FAILURE =
  'POST_CONSUL_CRM_PROSPECTO_FAILURE'

export const POST_CONSUL_VEHICLES_DETAIL = 'POST_CONSUL_VEHICLES_DETAIL'
export const POST_CONSUL_VEHICLES_DETAIL_SUCCESS =
  'POST_CONSUL_VEHICLES_DETAIL_SUCCESS'
export const POST_CONSUL_VEHICLES_DETAIL_FAILURE =
  'POST_CONSUL_VEHICLES_DETAIL_FAILURE'

export const POST_PERSONAL_MENU = 'POST_PERSONAL_MENU'
export const POST_PERSONAL_MENU_SUCCESS = 'POST_PERSONAL_MENU_SUCCESS'
export const POST_PERSONAL_MENU_FAILURE = 'POST_PERSONAL_MENU_FAILURE'

export const POST_PERSONAL = 'POST_PERSONAL'
export const POST_PERSONAL_SUCCESS = 'POST_PERSONAL_SUCCESS'
export const POST_PERSONAL_FAILURE = 'POST_PERSONAL_FAILURE'

export const POST_ADD_PERSONAL_ACTIVITY = 'POST_ADD_PERSONAL_ACTIVITY'
export const POST_ADD_PERSONAL_ACTIVITY_SUCCESS =
  'POST_ADD_PERSONAL_ACTIVITY_SUCCESS'
export const POST_ADD_PERSONAL_ACTIVITY_FAILURE =
  'POST_ADD_PERSONAL_ACTIVITY_FAILURE'

export const POST_CONSUL_PERSONAL_ACTIVITY = 'POST_CONSUL_PERSONAL_ACTIVITY'
export const POST_CONSUL_PERSONAL_ACTIVITY_SUCCESS =
  'POST_CONSUL_PERSONAL_ACTIVITY_SUCCESS'
export const POST_CONSUL_PERSONAL_ACTIVITY_FAILURE =
  'POST_CONSUL_PERSONAL_ACTIVITY_FAILURE'

export const PUT_PERSONAL_ACTIVITY = 'PUT_PERSONAL_ACTIVITY'
export const PUT_PERSONAL_ACTIVITY_SUCCESS = 'PUT_PERSONAL_ACTIVITY_SUCCESS'
export const PUT_PERSONAL_ACTIVITY_FAILURE = 'PUT_PERSONAL_ACTIVITY_FAILURE'

export const GET_SALES_INVENTORY = 'GET_SALES_INVENTORY'
export const GET_SALES_INVENTORY_SUCCESS = 'GET_SALES_INVENTORY_SUCCESS'
export const GET_SALES_INVENTORY_FAILURE = 'GET_SALES_INVENTORY_FAILURE'

export const POST_CONSUL_CLIENT = 'POST_CONSUL_CLIENT'
export const POST_CONSUL_CLIENT_SUCCESS = 'POST_CONSUL_CLIENT_SUCCESS'
export const POST_CONSUL_CLIENT_FAILURE = 'POST_CONSUL_CLIENT_FAILURE'

export const POST_ADD_RESERVATION_VEHICLE = 'POST_ADD_RESERVATION_VEHICLE'
export const POST_ADD_RESERVATION_VEHICLE_SUCCESS =
  'POST_ADD_RESERVATION_VEHICLE_SUCCESS'
export const POST_ADD_RESERVATION_VEHICLE_FAILURE =
  'POST_ADD_RESERVATION_VEHICLE_FAILURE'

export const PARAMETERS_GET_PARAMETERS_MULTI_LIST =
  'PARAMETERS_GET_GET_PARAMETERS_MULTI_LIST'
export const PARAMETERS_GET_PARAMETERS_MULTI_LIST_SUCCESS =
  'PARAMETERS_GET_GET_PARAMETERS_MULTI_LIST_SUCCESS'
export const PARAMETERS_GET_PARAMETERS_MULTI_LIST_FAILURE =
  'PARAMETERS_GET_GET_PARAMETERS_MULTI_LIST_FAILURE'
export const POST_ADD_LOCATION = 'POST_ADD_LOCATION'
export const POST_ADD_LOCATION_SUCCESS = 'POST_ADD_LOCATION_SUCCESS'
export const POST_ADD_LOCATION_FAILURE = 'POST_ADD_LOCATION_FAILURE'

export const POST_ADD_VEHICLE_SECTION = 'POST_ADD_VEHICLE_SECTION'
export const POST_ADD_VEHICLE_SECTION_SUCCESS =
  'POST_ADD_VEHICLE_SECTION_SUCCESS'
export const POST_ADD_VEHICLE_SECTION_FAILURE =
  'POST_ADD_VEHICLE_SECTION_FAILURE'

export const POST_CONSUL_VEHICLE_SECTION = 'POST_CONSUL_VEHICLE_SECTION'
export const POST_CONSUL_VEHICLE_SECTION_SUCCESS =
  'POST_CONSUL_VEHICLE_SECTION_SUCCESS'
export const POST_CONSUL_VEHICLE_SECTION_FAILURE =
  'POST_CONSUL_VEHICLE_SECTION_FAILURE'
export const PUT_LOCATION = 'PUT_LOCATION'
export const PUT_LOCATION_SUCCESS = 'PUT_LOCATION_SUCCESS'
export const PUT_LOCATION_FAILURE = 'PUT_LOCATION_FAILURE'

export const GET_BLACK_LIST = 'GET_BLACK_LIST'
export const GET_BLACK_LIST_SUCCESS = 'GET_BLACK_LIST_SUCCESS'
export const GET_BLACK_LIST_FAILURE = 'GET_BLACK_LIST_FAILURE'

export const POST_BLACK_LIST = 'POST_BLACK_LIST'
export const POST_BLACK_LIST_SUCCESS = 'POST_BLACK_LIST_SUCCESS'
export const POST_BLACK_LIST_FAILURE = 'POST_BLACK_LIST_FAILURE'

export const POST_OFERT = 'POST_OFERT'
export const POST_OFERT_SUCCESS = 'POST_OFERT_SUCCESS'
export const POST_OFERT_FAILURE = 'POST_OFERT_FAILURE'

export const PUT_BLACK_LIST = 'PUT_BLACK_LIST'
export const PUT_BLACK_LIST_SUCCESS = 'PUT_BLACK_LIST_SUCCESS'
export const PUT_BLACK_LIST_FAILURE = 'PUT_BLACK_LIST_FAILURE'

export const GET_REPRESENTATIVES = 'GET_REPRESENTATIVES'
export const GET_REPRESENTATIVES_SUCCESS = 'GET_REPRESENTATIVES_SUCCESS'
export const GET_REPRESENTATIVES_FAILURE = 'GET_REPRESENTATIVES_FAILURE'

export const POST_REPRESENTATIVES = 'POST_MANAGER_REPRESENTATIVES'
export const POST_REPRESENTATIVES_SUCCESS = 'POST_REPRESENTATIVES_SUCCESS'
export const POST_REPRESENTATIVES_FAILURE = 'POST_REPRESENTATIVES_FAILURE'

export const PUT_REPRESENTATIVES = 'PUT_REPRESENTATIVES'
export const PUT_REPRESENTATIVES_SUCCESS = 'PUT_REPRESENTATIVES_SUCCESS'
export const PUT_REPRESENTATIVES_FAILURE = 'PUT_REPRESENTATIVES_FAILURE'

export const PUT_ANALISIS_CREDIT = 'PUT_ANALISIS_CREDIT'
export const PUT_ANALISIS_CREDIT_SUCCESS = 'PUT_ANALISIS_CREDIT_SUCCESS'
export const PUT_ANALISIS_CREDIT_FAILURE = 'PUT_ANALISIS_CREDIT_FAILURE'

export const POST_ADM_COMPLIANCE_ANALIS = 'POST_ADM_COMPLIANCE_ANALIS'
export const POST_ADM_COMPLIANCE_ANALIS_SUCCESS =
  'POST_ADM_COMPLIANCE_ANALIS_SUCCESS'
export const POST_ADM_COMPLIANCE_ANALIS_FAILURE =
  'POST_ADM_COMPLIANCE_ANALIS_FAILURE'
export const POST_REPRESENT_ANALIS = 'POST_REPRESENT_ANALIS'
export const POST_REPRESENT_ANALIS_SUCCESS = 'POST_REPRESENT_ANALIS_SUCCESS'
export const POST_REPRESENT_ANALIS_FAILURE = 'POST_REPRESENT_ANALIS_FAILURE'

export const POST_CONSUL_CRM_ANALIS_CREDIT_INF =
  'POST_CONSUL_CRM_ANALIS_CREDIT_INF'
export const POST_CONSUL_CRM_ANALIS_CREDIT_INF_SUCCESS =
  'POST_CONSUL_CRM_ANALIS_CREDIT_INF_SUCCESS'
export const POST_CONSUL_CRM_ANALIS_CREDIT_INF_FAILURE =
  'POST_CONSUL_CRM_ANALIS_CREDIT_INF_FAILURE'

export const PUT_CRM_ANALIS_CREDIT = 'PUT_CRM_ANALIS_CREDIT'
export const PUT_CRM_ANALIS_CREDIT_SUCCESS = 'PUT_CRM_ANALIS_CREDIT_SUCCESS'
export const PUT_CRM_ANALIS_CREDIT_FAILURE = 'PUT_CRM_ANALIS_CREDIT_FAILURE'

export const RESET_STATE = 'RESET_STATE'
export const POST_COST_CENTER = 'POST_COST_CENTER'
export const POST_COST_CENTER_SUCCESS = 'POST_COST_CENTER_SUCCESS'
export const POST_COST_CENTER_FAILURE = 'POST_COST_CENTER_ANALIS_FAILURE'

export const POST_FINANCING_OFFER = 'POST_FINANCING_OFFER'
export const POST_FINANCING_OFFER_SUCCESS = 'POST_FINANCING_OFFER_SUCCESS'
export const POST_FINANCING_OFFER_FAILURE =
  'POST_FINANCING_OFFER_ANALIS_FAILURE'

export const POST_EMPLOYEE_LIST = 'POST_EMPLOYEE_LIST'
export const POST_EMPLOYEE_LIST_SUCCESS = 'POST_EMPLOYEE_LIST_SUCCESS'
export const POST_EMPLOYEE_LIST_FAILURE = 'POST_EMPLOYEE_LIST_FAILURE'

export const PUT_CRM_CLIENT = 'PUT_CRM_CLIENT'
export const PUT_CRM_CLIENT_SUCCESS = 'PUT_CRM_CLIENT_SUCCESS'
export const PUT_CRM_CLIENT_FAILURE = 'PUT_CRM_CLIENT_FAILURE'

export const GET_PHONE_PROSPECTO = 'GET_PHONE_PROSPECTO'
export const GET_PHONE_PROSPECTO_SUCCESS = 'GET_PHONE_PROSPECTO_SUCCESS'
export const GET_PHONE_PROSPECTO_FAILURE = 'GET_PHONE_PROSPECTO_FAILURE'

export const PUT_PHONE_PROSPECTO = ' PUT_PHONE_PROSPECTO'
export const PUT_PHONE_PROSPECTO_SUCCESS = 'PUT_PHONE_PROSPECTO_SUCCESS'
export const PUT_PHONE_PROSPECTO_FAILURE = 'PUT_PHONE_PROSPECTO_FAILURE'

export const POST_CONSUL_PHONE_PROSPECTO = 'POST_CONSUL_PHONE_PROSPECTO'
export const POST_CONSUL_PHONE_PROSPECTO_SUCCESS =
  'POST_CONSUL_PHONE_PROSPECTO_SUCCESS'
export const POST_CONSUL_PHONE_PROSPECTO_FAILURE =
  'POST_CONSUL_PHONE_PROSPECTO_FAILURE'

export const PUT_FINANCING_OFFER = 'PUT_FINANCING_OFFER'
export const PUT_FINANCING_OFFER_SUCCESS = 'PUT_FINANCING_OFFER_SUCCESS'
export const PUT_FINANCING_OFFER_FAILURE = 'PUT_FINANCING_OFFER_ANALIS_FAILURE'

export const POST_CRM_VEHICULE_INTEREST = 'POST_CRM_VEHICULE_INTEREST'
export const POST_CRM_VEHICULE_INTEREST_SUCCESS =
  'POST_CRM_VEHICULE_INTEREST_SUCCESS'
export const POST_CRM_VEHICULE_INTEREST_FAILURE =
  'POST_CRM_VEHICULE_INTEREST_FAILURE'

export const POST_CONSUL_CRM_CAPTACION_PROSPECTO =
  'POST_CONSUL_CRM_CAPTACION_PROSPECTO'
export const POST_CONSUL_CRM_CAPTACION_PROSPECTO_SUCCESS =
  'POST_CONSUL_CRM_CAPTACION_PROSPECTO_SUCCESS'
export const POST_CONSUL_CRM_CAPTACION_PROSPECTO_FAILURE =
  'POST_CONSUL_CRM_CAPTACION_PROSPECTO_FAILURE'
export const POST_CLOSE_SPEND = 'POST_CLOSE_SPEND'
export const POST_CLOSE_SPEND_SUCCESS = 'POST_CLOSE_SPEND_SUCCESS'
export const POST_CLOSE_SPEND_FAILURE = 'POST_CLOSE_SPEND_FAILURE'

export const GET_CLOSE_SPEND = 'GET_CLOSE_SPEND'
export const GET_CLOSE_SPEND_SUCCESS = 'GET_CLOSE_SPEND_SUCCESS'
export const GET_CLOSE_SPEND_FAILURE = 'GET_CLOSE_SPEND_FAILURE'

export const PUT_CLOSE_SPEND = 'PUT_CLOSE_SPEND'
export const PUT_CLOSE_SPEND_SUCCESS = 'PUT_CLOSE_SPEND_SUCCESS'
export const PUT_CLOSE_SPEND_FAILURE = 'PUT_CLOSE_SPEND_FAILURE'
export const GET_CLIENT_DIRECTION = 'GET_CLIENT_DIRECTION'
export const GET_CLIENT_DIRECTION_SUCCESS = 'GET_CLIENT_DIRECTION_SUCCESS'
export const GET_CLIENT_DIRECTION_FAILURE = 'GET_CLIENT_DIRECTION_FAILURE'
export const SET_STEP_POSITION_FOR_REGISTER_PHYSICAL_PERSON_FORM =
  'SET_STEP_POSITION_FOR_REGISTER_PHYSICAL_PERSON_FORM'
export const SET_DYNAMIC_STEP_POSITION = 'SET_DYNAMIC_STEP_POSITION'
export const SET_CURRENCY_RATE = 'SET_CURRENCY_RATE'
export const SET_COINS = 'SET_COINS'
export const SET_OPENINGS = 'SET_OPENINGS'

////////COOKIE KEY ///////
export const COOKIE_KEY_MENU_OPTION_SELECTED = 'menuoption'
